---
# metadata file for local_accounts role

galaxy_info:
  author: Your Name
  description: Role to manage local user accounts.
  company: MyCompany
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04
  galaxy_tags:
    - users
    - accounts

dependencies: []
